name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  format-checking:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check Prettier & ESLint
        run: pnpm run check

      - name: Run test Check
        run: pnpm run test
