name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  standard-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check Prettier
        run: pnpm run format:check

      - name: Check ESLint
        run: pnpm run lint

      - name: Run Test
        run: pnpm vitest
